### ISSUE TITLE
.env file

### ISSUE THREAD

**Issue by MicahRCM** [SyntonicApps/reddit-bot-example-node#1]
Hey. I noticed you didn't have a .env file in your repository. I tried creating one in my root folder with the correct information but continue to get the following error:

Error: Missing credentials passed to snoowrap constructor. You must pass an object contai
ning either (a) userAgent, clientId, clientSecret, and refreshToken properties, (b) userA
gent and accessToken properties, or (c) userAgent, clientId, clientSecret, username, and
password properties. For information, please read the docs at https://not-an-aardvark.git
hub.io/snoowrap/.
    at new snoowrap

Do I create a file named "example.env" then put the following in?

CLIENT_ID=B-q23423Idbug
CLIENT_SECRET=4429349ufuwersd-jiwer1
REDDIT_USER=exampleuser
REDDIT_PASS=examplepass

**Comment by andrewbrooke** [comment]
@Abromide you actually just name your env file `.env` rather than `example.env` and put it at the root project directory. The contents look correct, so try that and let me know 👍

**Comment by MicahRCM** [comment]
Worked perfectly, thank you!
